server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_user_db
    username: postgres
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true